# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente', models.AutoField(db_column='CodCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NombreCliente', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DetalleTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('A', 'ALTA'), ('M', 'MEDIA'), ('B', 'BAJA')], max_length=10)),
                ('archivo', models.FileField(db_column='Archivo', upload_to='')),
                ('descripcion', models.CharField(blank=True, db_column='DescripcionTicket', max_length=100, null=True)),
                ('estadoDetalleTickets', models.CharField(blank=True, db_column='EstadoDetalleTickets', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DetalleTickets',
            },
        ),
        migrations.CreateModel(
            name='EncargadoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(db_column='CodCliente', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Cliente')),
                ('codUsuario', models.ForeignKey(db_column='CodUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EncargadoClientes',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='NombrePersona', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codProyecto', models.AutoField(db_column='CodProyecto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NombreProyecto', max_length=200, null=True)),
                ('cliente', models.ForeignKey(db_column='CodCliente', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Cliente')),
            ],
            options={
                'db_table': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500)),
                ('usuarioCreador', models.CharField(blank=True, db_column='UsuarioCreador', max_length=200, null=True)),
                ('UsuarioModificador', models.CharField(blank=True, db_column='UsuarioModificador', max_length=200, null=True)),
                ('fechaCreacion', models.DateTimeField(db_column='FechaCreacion')),
                ('fechaModificacion', models.DateTimeField(db_column='FechaModificacion')),
                ('titulo', models.CharField(blank=True, db_column='TituloTicket', max_length=200, null=True)),
                ('cliente', models.ForeignKey(db_column='CodCliente', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Cliente')),
                ('codEncargadoCliente', models.ForeignKey(db_column='CodEncargadoCliente', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.EncargadoClientes')),
                ('codEstado', models.ForeignKey(db_column='CodEstado', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Estados')),
                ('codProyecto', models.ForeignKey(db_column='CodProyecto', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Proyecto')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TipoPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='DecripcionTipoPersona', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TipoPersonas',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='codTipoPersona',
            field=models.ForeignKey(db_column='CodTipoPersona', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.TipoPersonas'),
        ),
        migrations.AddField(
            model_name='personas',
            name='codUsuario',
            field=models.ForeignKey(db_column='CodUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalletickets',
            name='asignadoA',
            field=models.ForeignKey(blank=True, db_column='AsignadoA', null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Personas'),
        ),
        migrations.AddField(
            model_name='detalletickets',
            name='codTicket',
            field=models.ForeignKey(db_column='CodTicket', on_delete=django.db.models.deletion.CASCADE, to='ticketsApp.Tickets'),
        ),
    ]
