# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='UsuarioModificador',
            field=models.ForeignKey(db_column=b'UsuarioModificador', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
