# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, db_column=b'CorreoCliente', max_length=254, null=True),
        ),
    ]
