# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0002_auto_20170615_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='descripcion_ticket',
            field=models.CharField(blank=True, db_column=b'DescripcionTicket', max_length=500, null=True),
        ),
    ]
