# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, db_column=b'Archivo', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, db_column=b'FechaCreacion'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column=b'FechaModificacion'),
        ),
    ]
