# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0002_cliente_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='correo_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='detalleticket',
            old_name='descripcion',
            new_name='descripcion_ticket',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombre_persona',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre',
            new_name='nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='tipopersona',
            old_name='descripcion',
            new_name='descripcion_tipoPersona',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='estado',
            name='descripcion_estado',
            field=models.CharField(blank=True, db_column=b'DescripcionEstado', max_length=200, null=True),
        ),
    ]
