# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0003_auto_20170619_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='codTipoPersona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='codUsuario',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='UsuarioModificador',
            field=models.ForeignKey(db_column=b'UsuarioModificador', on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asignadoA',
            field=models.ForeignKey(blank=True, db_column=b'AsignadoA', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='TipoPersona',
        ),
    ]
