# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0004_auto_20170623_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, db_column=b'Archivo', null=True, upload_to=b'uploads/'),
        ),
    ]
